name: Deploy slidev presentation to GitHub Pages

on:
  push:
    branches:
      - presentation

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./presentation
        run: npm install

      - name: Build
        working-directory: ./presentation
        run: npx slidev build --base /canieatthemushroom/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: presentation/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
